---
- name: Deploy to a vagrant instance for development
  hosts: all
  become: true
  become_user: root

  vars_files:
    - vars/base.yml
    - vars/vagrant.yml
    - vars/secret.yml

  vars:
    git_repo: "https://{{ githubuser | urlencode }}:{{ githubpassword }}@github.com/BeagleInc/Rufus.git"
    app_env:
      STATIC_ASSET_PATH: "{{ app_location }}/collectstatic"
      AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
      DJANGO_DEBUG: "0"
      SOCKET_DOMAIN: 1
      EMAIL_BACKEND: smtp
      SYSLOG: 1

  roles:
    - base
    - postgres
    - web
    - postfix
    - supervisord
