# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-13 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_merge_20170917_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'DOCX'), (2, 'DOC'), (3, 'PDF'), (4, 'TXT'), (5, 'Image'), (6, 'ZIP')], null=True),
        ),
    ]
