# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-23 15:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0022_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_auto_process', models.BooleanField(default=True)),
                ('auto_cleanup_tools', jsonfield.fields.JSONField(default=[b'linebreakers', b'title/header/footer', b'table of contents', b'bullet points and listing', b'listing rewriting'])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
