# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20170505_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='libstatistic',
            name='copyleft',
            field=models.BooleanField(default=False),
        ),
    ]
