# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-11 16:10
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_libstatistic_copyleft'),
    ]

    operations = [
        migrations.AddField(
            model_name='libstatistic',
            name='orig_lics',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='libstatistic',
            name='treat_as',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
