# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 13:45
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_licensestatistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libstatistic',
            name='orig_lics',
            field=jsonfield.fields.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libstatistic',
            name='treat_as',
            field=jsonfield.fields.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
