# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-17 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20170714_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensestatistic',
            name='treat_as',
            field=models.CharField(max_length=100),
        ),
    ]
