# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-28 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20170727_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='public_repo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='report',
            name='successful',
            field=models.BooleanField(default=True),
        ),
    ]
