# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-03 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.CharField(default='default', max_length=4096),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='portal.Batch'),
        ),
        migrations.AlterField(
            model_name='report',
            name='json',
            field=models.TextField(default=b'{}'),
        ),
    ]
