# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-30 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_report_report_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=4096, unique=True)),
                ('api_name', models.CharField(max_length=4096, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='json',
            field=models.TextField(default=b'[]'),
        ),
    ]
