# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-16 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_merge_20171031_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordlist',
            name='origin',
            field=models.CharField(default='no initial keyword', max_length=4096),
            preserve_default=False,
        ),
    ]
