- include: create_users_and_groups.yml

- include: setup_git_repo.yml
  when: server_user != "vagrant"
  tags: deploy

#- include: setup_virtualenv.yml
#  tags: virtualenv

- include: setup_npm_modules.yml
  tags: deploy

- include: setup_django_app.yml
  tags: deploy

- include: set_file_permissions.yml
  when: server_user != "vagrant"
  tags: deploy
