---

- name: Install Required Packages
  apt: name="{{ item }}" state=latest update_cache=yes cache_valid_time=86400
  with_items:
  - nginx
  become: true
  become_user: root

- include: server.yml
  when:
    - env != "vagrant"

- include: vagrant.yml
  when:
    - env == "vagrant"

- name: Enable nginx Site Config
  file: src=/etc/nginx/sites-available/beagle dest=/etc/nginx/sites-enabled/beagle state=link
  notify: restart nginx
  become: true
  become_user: root

- name: Install python passlib
  apt:
    update_cache: true
    pkg: python-passlib
    state: installed
  become: true
  become_user: root

- htpasswd:
    path: /etc/nginx/htpasswd.users
    name: "{{ nginx_htpasswd_username }}"
    password: "{{ nginx_htpasswd_password }}"
  notify: restart nginx
  become: true
  become_user: root

- name: Remove default app from nginx
  file: name=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx
  become: true
  become_user: root
