---


- name: Create location for TLS data
  file: state=directory path="/etc/nginx/ssl/"
  become: true
  become_user: root

- name: Install TLS certificate and key
  copy: src="{{ item }}" dest=/etc/nginx/ssl/
  with_items:
  - files/beagle.ai.crt
  - files/beagle.ai.key
  become: true
  become_user: root

# - name: Set up dhparam
#   command: openssl dhparam -out /etc/nginx/ssl/dhparam.pem 4096 creates=/etc/nginx/ssl/dhparam.pem
#   become: true
#   become_user: root

- name: Install nginx Conf for Server
  template: src=nginx_beagle.j2 dest=/etc/nginx/sites-available/beagle force=true mode=0660
  notify: restart nginx
  become: true
  become_user: root
