# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-26 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_auto_20171123_1926'),
        ('watcher', '0003_cloudfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudfile',
            name='file_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.File'),
        ),
        migrations.AddField(
            model_name='cloudfolder',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Batch'),
        ),
    ]
