# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-04 15:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watcher', '0005_auto_20171127_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials', jsonfield.fields.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Google Drive Credentials',
            },
        ),
        migrations.AlterField(
            model_name='cloudfolder',
            name='cloud',
            field=models.CharField(choices=[('dropbox', 'Dropbox'), ('google_drive', 'Google Drive')], max_length=50),
        ),
    ]
