# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-06 16:52
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0006_auto_20171204_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudfolder',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='cloudfolder',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
