# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_file_need_ocr'),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content_file',
            field=models.FileField(null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='document',
            name='source_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.File'),
        ),
    ]
