# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_merge_20170616_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='origin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cleaned', to='document.Document'),
        ),
        migrations.AlterField(
            model_name='documenttag',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='document.Document'),
        ),
    ]
