# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_auto_20170809_1206'),
        ('document', '0007_auto_20170808_1322'),
    ]

    operations = [
    ]
