# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 12:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.CharField(choices=[(b'YEARLY_PAID_SUBSCRIPTION', b"<class 'marketing.subscriptions.YearlyPaidSubscription'>"), (b'MONTHLY_PAID_SUBSCRIPTION', b"<class 'marketing.subscriptions.MonthlyPaidSubscription'>")], help_text='The subscription package', max_length=200, verbose_name='Subscription')),
                ('expiration_date', models.DateTimeField()),
                ('buyer', models.ForeignKey(help_text='The user that bought something', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
