# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-30 07:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20170828_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Promo Code')),
                ('subscription', models.CharField(choices=[(b'MONTHLY_ENTERPRISE_SUBSCRIPTION', b"<class 'marketing.subscriptions.MonthlyEnterpriseSubscription'>"), (b'MONTHLY_PAID_SUBSCRIPTION', b"<class 'marketing.subscriptions.MonthlyPaidSubscription'>"), (b'YEARLY_ENTERPRISE_SUBSCRIPTION', b"<class 'marketing.subscriptions.YearlyEnterpriseSubscription'>"), (b'YEARLY_PAID_SUBSCRIPTION', b"<class 'marketing.subscriptions.YearlyPaidSubscription'>")], max_length=200, verbose_name='Subscription')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Coupon description')),
                ('free', models.BooleanField(default=False, verbose_name='Make it FREE?')),
                ('special_price', models.FloatField(blank=True, default=None, null=True, verbose_name='Special Price')),
                ('discount_percent', models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Discount(Percent)')),
                ('discount_units', models.FloatField(blank=True, default=None, null=True, verbose_name='Discount(Units)')),
                ('max_use_count', models.IntegerField(blank=True, default=None, help_text='Leave blank if no such restriction is desired', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='How many times the coupon can be used')),
                ('use_count', models.IntegerField(default=0, verbose_name='How many times the coupon has been used')),
                ('start_date', models.DateTimeField(blank=True, help_text='Optional', null=True, verbose_name='Coupon available from this date')),
                ('end_date', models.DateTimeField(blank=True, help_text='Optional', null=True, verbose_name='Coupon available until this date')),
            ],
        ),
        migrations.AddField(
            model_name='purchasedsubscription',
            name='coupon_used',
            field=models.ForeignKey(blank=True, help_text='The coupon the user used to get this subscription', null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.Coupon'),
        ),
    ]
