---

- name: Creates directory
  file:
    path="/srv/"
  become: true
  become_user: "{{ server_user }}"
  tags: git

- name: Ensure that the /srv/ file permissions are set properly
  file: path="/srv/"
        recurse=yes
        owner={{ server_user }}
        group={{ server_user }}
        state=directory
  become: true
  become_user: root

- name: Setup the Git repo
  git:
    repo={{ git_repo }}
    version={{ git_branch }}
    dest={{ project_path }}
    accept_hostkey=yes
    key_file={{ git_key_file }}
  when: setup_git_repo is defined and setup_git_repo
  tags: git
  become: true
  become_user: "{{ server_user }}"

- name: Delete all .pyc files
  command: find . -name '*.pyc' -delete
  args:
    chdir: "{{ project_path }}"
  tags: git
  become: true
  become_user: root
