# Generated by Django 2.2 on 2021-03-17 21:03

import collections
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import ml.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.CharField(max_length=100, unique=True, verbose_name='UUID')),
                ('samples', jsonfield.fields.JSONField(blank=True, default=None, load_kwargs={'object_pairs_hook': collections.OrderedDict}, null=True, verbose_name='Samples')),
            ],
            options={
                'abstract': False,
            },
            bases=(ml.models.SetSizeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PretrainedLearner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.CharField(max_length=100, unique=True, verbose_name='UUID')),
                ('tag', models.CharField(db_index=True, max_length=300, verbose_name='Tag')),
                ('description', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Description')),
                ('model_type', models.CharField(choices=[('logreg', 'Logistic Regression'), ('mlp', 'Multi-layer Perceptron'), ('rf', 'Random Forest'), ('adaboost', 'AdaBoost SVM')], default='logreg', max_length=10, verbose_name='Model Type')),
                ('exclusivity', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Exclusive to:')),
            ],
            options={
                'abstract': False,
            },
            bases=(ml.models.ModelS3Mixin, ml.models.VectorizerS3Mixin, models.Model),
        ),
        migrations.CreateModel(
            name='OnlineLearner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.CharField(max_length=100, unique=True, verbose_name='UUID')),
                ('tag', models.CharField(db_index=True, max_length=300, verbose_name='Tag')),
                ('pretrained', models.BooleanField(default=False, verbose_name='Pretrained')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('dataset', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='learner', to='ml.OnlineDataset')),
                ('experiment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='online_learners', to='experiment.Experiment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(ml.models.ModelS3Mixin, ml.models.SetSizeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LearnerAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.CharField(max_length=100, unique=True, verbose_name='UUID')),
                ('tag', models.CharField(db_index=True, max_length=300, verbose_name='Tag')),
                ('description', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Description')),
                ('model_type', models.CharField(choices=[('logreg', 'Logistic Regression'), ('mlp', 'Multi-layer Perceptron'), ('rf', 'Random Forest'), ('adaboost', 'AdaBoost SVM')], default='logreg', max_length=10, verbose_name='Model Type')),
                ('name', models.CharField(blank=True, default='', max_length=300, verbose_name='Name')),
                ('output_range', jsonfield.fields.JSONField(blank=True, default=None, null=True)),
                ('parent_learner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learner_attribute', to='ml.PretrainedLearner')),
            ],
            options={
                'abstract': False,
            },
            bases=(ml.models.ModelS3Mixin, ml.models.VectorizerS3Mixin, models.Model),
        ),
    ]
