# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-18 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerattribute',
            name='model_type',
            field=models.CharField(choices=[(b'logreg', b'Logistic Regression'), (b'mlp', b'Multi-layer Perceptron')], default=b'logreg', max_length=10, verbose_name=b'Model Type'),
        ),
        migrations.AddField(
            model_name='pretrainedlearner',
            name='model_type',
            field=models.CharField(choices=[(b'logreg', b'Logistic Regression'), (b'mlp', b'Multi-layer Perceptron')], default=b'logreg', max_length=10, verbose_name=b'Model Type'),
        ),
    ]
