# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-27 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0004_auto_20170726_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerattribute',
            name='tag',
            field=models.CharField(db_index=True, max_length=300, verbose_name=b'Tag'),
        ),
        migrations.AlterField(
            model_name='onlinelearner',
            name='tag',
            field=models.CharField(db_index=True, max_length=300, verbose_name=b'Tag'),
        ),
        migrations.AlterField(
            model_name='pretrainedlearner',
            name='tag',
            field=models.CharField(db_index=True, max_length=300, verbose_name=b'Tag'),
        ),
    ]
