# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-25 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0009_auto_20170825_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinelearner',
            name='positive_set_size',
        ),
    ]
