# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-08 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170804_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experimentcollaborationinvite',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='experimentexternalinvite',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='experimentexternalinvite',
            name='pending',
        ),
    ]
