# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 10:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dataset', '0010_dataset_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20170808_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetCollaborationInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_invites', to='dataset.Dataset')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_collaboration_invites_received', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_collaboration_invites_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DatasetExternalInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('email', models.EmailField(max_length=254)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_invites', to='dataset.Dataset')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_external_invites_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='experimentcollaborationinvite',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_collaboration_invites_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='experimentcollaborationinvite',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_collaboration_invites_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='experimentexternalinvite',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_external_invites_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
