# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-17 20:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud', models.CharField(choices=[('dropbox', 'Dropbox')], max_length=50)),
                ('folder_id', models.CharField(max_length=100, unique=True)),
                ('folder_path', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Folders',
            },
        ),
    ]
