# Generated by Django 2.2 on 2021-05-11 19:09

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googledriveaccess',
            name='credentials',
            field=jsonfield.fields.JSONField(),
        ),
    ]
