# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-17 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0002_cloudfolder'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=100, unique=True)),
                ('file_name', models.CharField(max_length=100)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='watcher.CloudFolder')),
            ],
            options={
                'verbose_name_plural': 'Files',
            },
        ),
    ]
