# Generated by Django 2.2 on 2021-02-26 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0008_auto_20171206_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudfile',
            name='file_object',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.File'),
        ),
        migrations.AlterField(
            model_name='cloudfile',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='files', to='watcher.CloudFolder'),
        ),
        migrations.AlterField(
            model_name='cloudfolder',
            name='batch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Batch'),
        ),
        migrations.AlterField(
            model_name='cloudfolder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dropboxaccess',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='googledriveaccess',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
