# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-30 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_report_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='json',
            field=models.TextField(default=b'[]'),
        ),
    ]
