---


application_name: kibble
update_apt_cache: yes
app_location: "/srv/{{ application_name }}"

security_group_name: "{{ application_name }}_security_group"
region: ca-central-1
ami_id: ami-ff902d9b
instance_type: t2.small

GUNICORN_DJANGO_PORT: 8001
NODE_SOCKET_SERVER_PORT: 4000

create_superuser: yes

AWS_SECRET_ACCESS_KEY: null
AWS_ACCESS_KEY_ID: null
AWS_STORAGE_BUCKET_NAME: null
AWS_S3_REGION_NAME: null
DROPBOX_APP_KEY: null
DROPBOX_APP_SECRET: null
GOOGLE_DRIVE_CLIENT_ID: null
GOOGLE_DRIVE_CLIENT_SECRET: null
