# Generated by Django 2.2 on 2021-03-13 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import portal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('upload_error', models.CharField(blank=True, max_length=50, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('process_time', models.TimeField(blank=True, null=True)),
                ('personal_data_gathered', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'batches',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Archived')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_file', models.FileField(null=True, upload_to='project_archives/')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='archive', to='portal.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_auto_process', models.BooleanField(default=True)),
                ('auto_cleanup_tools', jsonfield.fields.JSONField(default=['title/header/footer', 'table of contents', 'bullet points and listing', 'listing rewriting'])),
                ('obfuscate_string', models.CharField(default='[[CONFIDENTIAL]]', max_length=255)),
                ('highlight_color', models.CharField(default='red', max_length=16)),
                ('auto_gather_personal_data', models.BooleanField(default=False)),
                ('obfuscated_export_ext', models.CharField(default='PDF', max_length=4)),
                ('sentence_word_threshold', models.SmallIntegerField(default=8)),
                ('personal_data_types', jsonfield.fields.JSONField(default={'Date': (True, 'string'), 'Email': (True, 'string'), 'Link': (True, 'string'), 'Organization': (True, 'string'), 'Person': (True, 'string'), 'Phone': (True, 'string'), 'Price': (True, 'string'), 'Street Address': (True, 'string')})),
                ('min_similarity_score', models.FloatField(default=3.5)),
                ('auth_token', models.CharField(max_length=40, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='keywordlists', to='portal.Batch')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='project',
            field=models.ManyToManyField(related_name='batches', to='portal.Project'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200, null=True)),
                ('content', models.FileField(max_length=400, upload_to=portal.models.make_upload_path)),
                ('need_ocr', models.NullBooleanField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.IntegerField(choices=[(0, 'Unknown'), (1, 'DOCX'), (2, 'DOC'), (3, 'PDF'), (4, 'TXT'), (5, 'Image'), (6, 'ZIP'), (7, 'HTML'), (8, 'XML')], null=True)),
                ('auto_processed', models.CharField(max_length=7, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='files', to='portal.Batch')),
            ],
            options={
                'unique_together': {('file_name', 'batch')},
            },
        ),
    ]
