# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20170525_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='project_name',
        ),
    ]
