# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20170523_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='batch',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='portal.Project'),
        ),
        migrations.AddField(
            model_name='keywordlist',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keywordlist', to='portal.Batch'),
        ),
    ]
