# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 14:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_merge_20170529_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='keywordlist',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keywordlists', to='portal.Batch'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
