# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20170530_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='need_ocr',
            field=models.BooleanField(default=False),
        ),
    ]
