# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-31 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_merge_20170609_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='party_a',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='party_b',
        ),
    ]
