# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-28 10:42
from __future__ import unicode_literals

from django.db import migrations, models


def migrate_project(apps, schema_editor):
    Batch = apps.get_model('portal', 'Batch')
    for row in Batch.objects.all():
        if row.project:
            row.projects.add(row.project)
            row.save()


def migrate_project_rev(apps, schema_editor):
    Batch = apps.get_model('portal', 'Batch')
    for row in Batch.objects.all():
        if row.project:
            row.project = row.projects.first()
            row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_merge_20170609_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='projects',
            field=models.ManyToManyField(to='portal.Project'),
        ),
        migrations.RunPython(migrate_project, migrate_project_rev),
    ]
