# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_merge_20170609_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.FileField(max_length=400, upload_to=portal.models.make_upload_path),
        ),
    ]
