# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-28 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_batch_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='project',
        ),
        migrations.AlterField(
            model_name='batch',
            name='projects',
            field=models.ManyToManyField(related_name='batches', to='portal.Project'),
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='projects',
            new_name='project',
        ),
    ]
