# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-06 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_projectarchive'),
        ('portal', '0012_merge_20170803_1615'),
    ]

    operations = [
    ]
