# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-23 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_merge_20170809_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set([('file_name', 'batch')]),
        ),
    ]
