# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-23 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_auto_20170823_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Archived')], default=0),
        ),
    ]
