# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-25 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20170823_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='projectarchive',
            name='content_file',
            field=models.FileField(null=True, upload_to='project_archives/'),
        ),
    ]
