# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-28 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_auto_20170825_0044'),
        ('portal', '0015_auto_20170823_1926'),
    ]

    operations = [
    ]
