# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-01 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_auto_20170831_1924'),
        ('portal', '0018_merge_20170828_1109'),
    ]

    operations = [
    ]
