# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-07 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_auto_20170906_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrstatus',
            name='document_quality',
            field=models.SmallIntegerField(choices=[(1, b'NO_OCR'), (2, b'LOW_OCR'), (3, b'STANDARD_OCR'), (4, b'HIGH_OCR')], null=True),
        ),
        migrations.AlterField(
            model_name='ocrstatus',
            name='status',
            field=models.SmallIntegerField(choices=[(10, b'UPLOADED'), (20, b'SUBMITTED'), (30, b'PROCESSING'), (40, b'PROCESSED'), (45, b'ANALYZED'), (50, b'DOWNLOADED'), (55, b'DELETED'), (60, b'ERROR')], null=True),
        ),
        migrations.AlterField(
            model_name='ocrstatus',
            name='word_quality',
            field=models.SmallIntegerField(choices=[(1, b'STANDARD_OCR'), (2, b'HIGH_SPECIAL_CHARS'), (3, b'HIGH_NUMERIC_CHARS')], null=True),
        ),
    ]
