# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-23 19:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


def create_profiles_of_legacy_users(apps, schema_editor):
    """ Creates a Profile for each legacy User. """
    user_app_label, user_model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(user_app_label, user_model_name)
    Profile = apps.get_model('portal', 'Profile')
    for user in User.objects.all():
        Profile.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0023_profile'),
    ]

    operations = [
        migrations.RunPython(
            create_profiles_of_legacy_users,
            migrations.RunPython.noop,  # no reverse code needed
        )
    ]
