# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-08 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0027_auto_20171214_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name_plural': 'batches'},
        ),
        migrations.AlterModelOptions(
            name='ocrstatus',
            options={'verbose_name_plural': 'OCR statuses'},
        ),
    ]
