# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-28 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0028_auto_20180208_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrstatus',
            name='content',
        ),
        migrations.DeleteModel(
            name='OCRStatus',
        ),
    ]
