# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-19 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_auto_20180228_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='highlight_color',
            field=models.CharField(default=b'red', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='obfuscate_string',
            field=models.CharField(default=b'[[CONFIDENTIAL]]', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='obfuscate_type',
            field=models.CharField(default=b'string', max_length=10),
        ),
    ]
