# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-09 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0035_file_auto_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='obfuscated_export_ext',
            field=models.CharField(default=b'PDF', max_length=4),
        ),
    ]
