# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-12 12:53
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0036_profile_obfuscated_export_ext'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personal_data_types',
            field=jsonfield.fields.JSONField(default={'Canadian Social Insurance Number': True, 'Date': True, 'Email': True, 'Link': True, 'Organization': True, 'Person': True, 'Phone': True, 'Price': True, 'Street Address': True, 'UK National Insurance Number': True, 'US Social Security Number': True}),
        ),
    ]
