# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-15 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0037_profile_personal_data_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'DOCX'), (2, 'DOC'), (3, 'PDF'), (4, 'TXT'), (5, 'Image'), (6, 'ZIP'), (7, 'HTML'), (8, 'XML')], null=True),
        ),
    ]
