# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-18 17:49
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0038_auto_20180315_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='auto_cleanup_tools',
            field=jsonfield.fields.JSONField(default=[b'title/header/footer', b'table of contents', b'bullet points and listing', b'listing rewriting']),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personal_data_types',
            field=jsonfield.fields.JSONField(default={b'Date': True, b'Email': True, b'Link': True, b'Organization': True, b'Person': True, b'Phone': True, b'Price': True, b'Street Address': True}),
        ),
    ]
