# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-18 17:49
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0038_auto_20180315_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='auto_cleanup_tools',
            field=jsonfield.fields.JSONField(default=['title/header/footer', 'table of contents', 'bullet points and listing', 'listing rewriting']),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personal_data_types',
            field=jsonfield.fields.JSONField(default={'Date': True, 'Email': True, 'Link': True, 'Organization': True, 'Person': True, 'Phone': True, 'Price': True, 'Street Address': True}),
        ),
    ]
