# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-28 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0039_auto_20180318_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='min_similarity_score',
            field=models.FloatField(default=3.5),
        ),
    ]
