# Generated by Django 2.2 on 2021-02-26 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0042_auto_20180402_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='file',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='files', to='portal.Batch'),
        ),
        migrations.AlterField(
            model_name='keywordlist',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='keywordlists', to='portal.Batch'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='highlight_color',
            field=models.CharField(default='red', max_length=16),
        ),
        migrations.AlterField(
            model_name='profile',
            name='obfuscate_string',
            field=models.CharField(default='[[CONFIDENTIAL]]', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='obfuscated_export_ext',
            field=models.CharField(default='PDF', max_length=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectarchive',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='archive', to='portal.Project'),
        ),
    ]
