---

- include: create_swap_file.yml
  when: create_swap_file
  tags: swap

- name: Ensure bash, OpenSSL, and libssl are the latest versions
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=latest
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc
  async: 0
  poll: 0
  tags: packages
  become: true
  become_user: root

- name: Install Base Packages
  apt: name={{ item }} state=latest update_cache=true cache_valid_time=86400
  with_items:
    - build-essential
    - acl
    - git

    # Python
    - python3
    - python3-dev
    - python3-pip
    #- python3-virtualenv
    - virtualenv
    - ipython

    # libxml for lxml package (python requirement)
    - libxml2-dev
    - libxslt1-dev

    # Scipy required
    - gfortran
    - libopenblas-dev
    - liblapack-dev

    # Misc
    - supervisor
    - libpq-dev
    - libffi-dev
    - docx2txt
    - libjpeg-dev
    - libreoffice
  tags: packages
  become: true
  become_user: root

- name: Upgrade pip
  pip: name=pip state=latest
  tags: packages
  