# Generated by Django 2.2 on 2021-03-24 21:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Promo Code')),
                ('subscription', models.CharField(choices=[('TWO_MONTHS_LIMITED_EDITION_SUBSCRIPTION', "<class 'dogbone.app_settings.marketing_settings.TwoMonthsLimitedEditionPaidSubscription'>"), ('EXTENDED_ALL_ACCESS_TRIAL', "<class 'dogbone.app_settings.marketing_settings.ExtendedAllAccessTrial'>"), ('MONTHLY_PAID_SUBSCRIPTION', "<class 'dogbone.app_settings.marketing_settings.MonthlyPaidSubscription'>"), ('ALL_ACCESS_TRIAL', "<class 'dogbone.app_settings.marketing_settings.AllAccessTrial'>"), ('YEARLY_PAID_SUBSCRIPTION', "<class 'dogbone.app_settings.marketing_settings.YearlyPaidSubscription'>"), ('6MO_STANDARD_TRIAL', "<class 'dogbone.app_settings.marketing_settings.SixMonthsTrial'>"), ('UNLIMITED_BROWSER_EXTENSION_SUBSCRIPTION', "<class 'dogbone.app_settings.marketing_settings.UnlimitedBrowserExtensionSubscription'>"), ('3MO_STANDARD_TRIAL', "<class 'dogbone.app_settings.marketing_settings.ThreeMonthsTrial'>"), ('PREMIUM_MONTHLY_PAID_SUBSCRIPTION', "<class 'dogbone.app_settings.marketing_settings.PremiumMonthlyPaidSubscription'>"), ('STANDARD_TRIAL', "<class 'dogbone.app_settings.marketing_settings.StandardTrial'>"), ('PREMIUM_YEARLY_PAID_SUBSCRIPTION', "<class 'dogbone.app_settings.marketing_settings.PremiumYearlyPaidSubscription'>"), ('TWO_WEEK_ALL_ACCESS_TRIAL', "<class 'dogbone.app_settings.marketing_settings.TwoWeekAllAccessTrial'>")], max_length=200, verbose_name='Subscription')),
                ('notes', models.TextField(blank=True, help_text='Stuff you should remember about this coupon', null=True, verbose_name='Notes')),
                ('free', models.BooleanField(default=False, help_text='Makes the subscription FREE', verbose_name='Make it FREE?')),
                ('special_price', models.FloatField(blank=True, default=None, help_text='A special price to a given subscription (in the currency of the subscription)', null=True, verbose_name='Special Price')),
                ('discount_percent', models.FloatField(blank=True, default=None, help_text='A discount (in percents) to a given subscription', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Discount(Percent)')),
                ('discount_units', models.FloatField(blank=True, default=None, help_text='A discount (in units) to a given subscription', null=True, verbose_name='Discount(Units)')),
                ('max_use_count', models.IntegerField(blank=True, default=None, help_text='Leave blank if no such restriction is desired', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='How many times the coupon can be used')),
                ('use_count', models.IntegerField(default=0, help_text='Helpful tracker of the popularity of coupons', verbose_name='How many times the coupon has been used')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchasedSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('subscription', models.CharField(choices=[('TWO_MONTHS_LIMITED_EDITION_SUBSCRIPTION', "<class 'dogbone.app_settings.marketing_settings.TwoMonthsLimitedEditionPaidSubscription'>"), ('EXTENDED_ALL_ACCESS_TRIAL', "<class 'dogbone.app_settings.marketing_settings.ExtendedAllAccessTrial'>"), ('MONTHLY_PAID_SUBSCRIPTION', "<class 'dogbone.app_settings.marketing_settings.MonthlyPaidSubscription'>"), ('ALL_ACCESS_TRIAL', "<class 'dogbone.app_settings.marketing_settings.AllAccessTrial'>"), ('YEARLY_PAID_SUBSCRIPTION', "<class 'dogbone.app_settings.marketing_settings.YearlyPaidSubscription'>"), ('6MO_STANDARD_TRIAL', "<class 'dogbone.app_settings.marketing_settings.SixMonthsTrial'>"), ('UNLIMITED_BROWSER_EXTENSION_SUBSCRIPTION', "<class 'dogbone.app_settings.marketing_settings.UnlimitedBrowserExtensionSubscription'>"), ('3MO_STANDARD_TRIAL', "<class 'dogbone.app_settings.marketing_settings.ThreeMonthsTrial'>"), ('PREMIUM_MONTHLY_PAID_SUBSCRIPTION', "<class 'dogbone.app_settings.marketing_settings.PremiumMonthlyPaidSubscription'>"), ('STANDARD_TRIAL', "<class 'dogbone.app_settings.marketing_settings.StandardTrial'>"), ('PREMIUM_YEARLY_PAID_SUBSCRIPTION', "<class 'dogbone.app_settings.marketing_settings.PremiumYearlyPaidSubscription'>"), ('TWO_WEEK_ALL_ACCESS_TRIAL', "<class 'dogbone.app_settings.marketing_settings.TwoWeekAllAccessTrial'>")], help_text='The subscription package', max_length=200, verbose_name='Subscription')),
                ('expired', models.BooleanField(default=False, verbose_name='Is expired')),
                ('expire_info_emailed', models.DateTimeField(blank=True, help_text='Email informing that the subscription is about to expire', null=True, verbose_name='About to expire email DateTime')),
                ('expire_warning_emailed', models.DateTimeField(blank=True, help_text='Email warning that the subscription has expired', null=True, verbose_name='Expired email DateTime')),
                ('buyer', models.ForeignKey(help_text='The user that bought something', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('coupon_used', models.ForeignKey(blank=True, help_text='The coupon the user used to get this subscription', null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.Coupon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.FloatField(verbose_name='Paid Amount')),
                ('currency', models.TextField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('CAN', 'CAN')], verbose_name='Currency')),
                ('ip_address', models.GenericIPAddressField(null=True, verbose_name='Address')),
                ('browser', models.TextField(null=True, verbose_name='Browser')),
                ('processing_time', models.FloatField(null=True, verbose_name='Processing Time in seconds')),
                ('transaction_id', models.TextField(max_length=200, null=True, verbose_name='3rd Party Transaction ID')),
                ('buyer', models.ForeignKey(help_text='The user that bought something', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('purchased_subscription', models.ForeignKey(help_text='What the user bought', on_delete=django.db.models.deletion.CASCADE, to='marketing.PurchasedSubscription')),
                ('redeemed_coupon', models.ForeignKey(help_text='In case the user redeemed a coupon', null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.Coupon')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
