# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-27 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import document.models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_documenttag_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content_file',
            field=models.FileField(max_length=400, null=True, upload_to=document.models.make_upload_path),
        ),
        migrations.AlterField(
            model_name='document',
            name='text_file',
            field=models.FileField(max_length=400, null=True, upload_to=document.models.make_upload_path),
        ),
    ]
