# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-19 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0012_sentence_vectorization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentence',
            options={'ordering': ['id']},
        ),
    ]
