# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-25 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='error',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='success',
            field=models.NullBooleanField(),
        ),
    ]
