# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-01 17:10
from __future__ import unicode_literals

import core.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default=core.models.generate_random_token, max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='A token value must be an alphanumeric string of a size between 50 and 100 characters long.', regex=re.compile('^[a-zA-Z0-9]{50,100}$'))], verbose_name='Value')),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
