# Generated by Django 2.2 on 2021-03-24 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(choices=[('open_widget_view', 'Open Widget View'), ('open_context_view', 'Open Context View'), ('open_detail_view', 'Open Detail View'), ('open_clause_view', 'Open Clause View'), ('document_uploaded', 'Document Uploaded'), ('document_processed', 'Document Processed'), ('document_conversion_error', 'Document Conversion Error'), ('document_language_error', 'Document Language Error'), ('document_too_large_to_ocr', 'Document too large to OCR')], max_length=100)),
                ('data', jsonfield.fields.JSONField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
