# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import portal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('upload_error', models.CharField(blank=True, max_length=50)),
                ('upload_date', models.DateTimeField(auto_now=True, null=True)),
                ('upload_time', models.TimeField(null=True)),
                ('process_time', models.TimeField(null=True)),
                ('party_a', models.CharField(blank=True, max_length=100)),
                ('party_b', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=portal.models.make_upload_path)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='portal.Batch')),
            ],
        ),
    ]
