# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_file_need_ocr'),
        ('portal', '0007_auto_20170608_1319'),
    ]

    operations = [
    ]
