# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-09 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_merge_20170608_1813'),
        ('portal', '0008_auto_20170606_2119'),
    ]

    operations = [
    ]
