# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-06 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_merge_20170609_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_file', models.FileField(upload_to='project_archives/')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='portal.Project')),
            ],
        ),
    ]
