# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-03 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20170728_1052'),
        ('portal', '0011_batch_owner'),
    ]

    operations = [
    ]
