# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-17 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_merge_20170901_1245'),
        ('portal', '0020_auto_20170907_1458'),
    ]

    operations = [
    ]
