# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-07 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_auto_20171207_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='process_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
