# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-14 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_auto_20171207_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='portal.Batch'),
        ),
    ]
