# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-28 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0031_auto_20180221_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auto_gather_personal_data',
            field=models.BooleanField(default=False),
        ),
    ]
