# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-05 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0034_profile_sentence_word_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='auto_processed',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
