# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-02 10:27
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


def update_personal_data_types(apps, schema_editor):
    """ Updates a Profile's personal_data_types field for each User. """

    Profile = apps.get_model('portal', 'Profile')

    for profile in Profile.objects.all():
        for key in profile.personal_data_types:
            profile.personal_data_types[key] = (profile.personal_data_types[key], 'string')
        profile.save()


def revert_personal_data_types(apps, schema_editor):
    """ Reverts a Profile's personal_data_types field for each User. """

    Profile = apps.get_model('portal', 'Profile')

    for profile in Profile.objects.all():
        for key in profile.personal_data_types:
            profile.personal_data_types[key] = profile.personal_data_types[key][0]
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0041_profile_auth_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='obfuscate_type',
        ),
        migrations.AlterField(
            model_name='profile',
            name='personal_data_types',
            field=jsonfield.fields.JSONField(default={b'Date': (True, b'string'), b'Email': (True, b'string'), b'Link': (True, b'string'), b'Organization': (True, b'string'), b'Person': (True, b'string'), b'Phone': (True, b'string'), b'Price': (True, b'string'), b'Street Address': (True, b'string')}),
        ),
        migrations.RunPython(
            update_personal_data_types,
            revert_personal_data_types
        )
    ]
