# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_detail_host_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='base',
            new_name='domain',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='host_name',
            new_name='protocol',
        ),
    ]
