# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-26 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0003_auto_20170726_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerattribute',
            name='uuid',
            field=models.CharField(max_length=100, unique=True, verbose_name=b'UUID'),
        ),
        migrations.AlterField(
            model_name='onlinelearner',
            name='uuid',
            field=models.CharField(max_length=100, unique=True, verbose_name=b'UUID'),
        ),
        migrations.AlterField(
            model_name='pretrainedlearner',
            name='uuid',
            field=models.CharField(max_length=100, unique=True, verbose_name=b'UUID'),
        ),
    ]
