# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-27 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0006_onlinelearner_experiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinelearner',
            name='experiment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='learners', to='experiment.Experiment'),
        ),
    ]
