# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-25 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0008_remove_onlinelearner_model_s3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerattribute',
            name='model_type',
            field=models.CharField(choices=[(b'logreg', b'Logistic Regression'), (b'mlp', b'Multi-layer Perceptron'), (b'rf', b'Random Forest'), (b'adaboost', b'AdaBoost SVM')], default=b'logreg', max_length=10, verbose_name=b'Model Type'),
        ),
        migrations.AlterField(
            model_name='onlinelearner',
            name='experiment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='online_learners', to='experiment.Experiment'),
        ),
        migrations.AlterField(
            model_name='pretrainedlearner',
            name='model_type',
            field=models.CharField(choices=[(b'logreg', b'Logistic Regression'), (b'mlp', b'Multi-layer Perceptron'), (b'rf', b'Random Forest'), (b'adaboost', b'AdaBoost SVM')], default=b'logreg', max_length=10, verbose_name=b'Model Type'),
        ),
    ]
