# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-23 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import incoming.models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0003_auto_20170926_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(blank=True, max_length=300, null=True)),
                ('attachment', models.FileField(null=True, upload_to=incoming.models.attachment_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='document_name',
        ),
        migrations.AddField(
            model_name='user',
            name='email_raw',
            field=models.FileField(blank=True, null=True, upload_to=incoming.models.raw_upload_to),
        ),
        migrations.AddField(
            model_name='attachment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incoming.User'),
        ),
    ]
