# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20170606_2119'),
        ('document', '0003_auto_20170614_1431'),
    ]

    operations = [
    ]
