# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-08 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentence',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
