# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_sentence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content_file',
            field=models.FileField(max_length=400, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='document',
            name='text_file',
            field=models.FileField(max_length=400, null=True, upload_to=b''),
        ),
    ]
