# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-17 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_merge_20170809_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttag',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
