# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-09 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0013_auto_20180219_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='selected',
            field=models.BooleanField(default=True),
        ),
    ]
