# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-15 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0015_custompersonaldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompersonaldata',
            name='is_rgx',
            field=models.BooleanField(default=False),
        ),
    ]
