---


- name: "Permissions on {{ app_location }}"
  file:
    state=directory
    path="{{ app_location }}"
    owner="{{ run_user }}"
    group="{{ run_user }}"
    mode=2775
  become: true
  become_user: root

- name: Setup the Git repo
  git:
    repo="{{ git_repo }}"
    dest="{{ app_location }}"
    accept_hostkey=yes
    version="{{ branch | mandatory }}"
  when:
    - env != "vagrant"  # Avoid cloning as the files are already synced

- name: "Permissions on {{ virtualenv_path }}"
  file:
    state=directory
    path="{{ virtualenv_path }}"
    owner="{{ run_user }}"
    group="{{ run_user }}"
    mode=2775
  become: true
  become_user: root

- name: Upgrade pip in virtualenv
  pip:
    name=pip
    state=latest
    virtualenv="{{ virtualenv_path }}"
  tags: packages

- name: Upgrade setuptools in virtualenv
  pip:
    name=setuptools
    state=latest
  tags: packages

- name: Pip the Packages
  pip:
    requirements="{{ app_location }}/requirements.txt"
    virtualenv="{{ virtualenv_path }}"

- name: "Permissions on {{ app_env.NLTK_DATA }}"
  file:
    state=directory
    path="{{ app_env.NLTK_DATA }}"
    owner="{{ run_user }}"
    group="{{ run_user }}"
    mode=2775
  become: true
  become_user: root

- name: Install nltk
  become: true
  become_user: "{{ run_user }}"
  shell: . "{{ virtualenv_path }}/bin/activate"; env NLTK_DATA="{{ app_env.NLTK_DATA }}" python -m nltk.downloader book

- name: Create the production django settings file
  template:
    src=production_settings.j2
    dest={{ app_location }}/{{ application_name }}/app_settings/production_settings.py
