---

- name: Install Required Packages
  apt: name={{ item }} state=latest update_cache=true cache_valid_time=86400
  with_items:
  - build-essential
  - libpq-dev
  - git-core
  - libffi-dev
  - python3-setuptools
  - libevent-dev
  - libssl-dev


  # Python
  - python3
  - python3-dev
  - python3-pip
  - python3-virtualenv
  - virtualenv
  - ipython
  # libxml for lxml package (python requirement)
  - libxml2-dev
  - libxslt1-dev


  # for scipy
  - gfortran
  - libopenblas-dev
  - liblapack-dev
  become: true
  become_user: root

- name: Upgrade setuptools
  pip: name=setuptools state=latest
  tags: packages


- name: Upgrade pip
  pip: name=pip state=latest
  tags: packages
