---

- include: install_packages.yml

- include: init_project.yml

- include: setup_npm_modules.yml
  when: env != "vagrant"  # Not working well on vagrant
  tags: deploy

- include: static_assets.yml

- include: run_manage.yml

- name: Run Fabric deploy
  local_action: "shell cd $(git rev-parse --git-dir) && fab -H {{ ansible_user }}@{{ inventory_hostname }} --set environment={{ env | mandatory }} deploy:{{ branch | mandatory }}"
  tags:
    - deploy
  when:
    - deploy_fabric is defined
