# Generated by Django 2.2 on 2021-03-24 21:41

import collections
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PretrainedLearner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('model_uuid', models.CharField(max_length=100, unique=True, verbose_name='Model UUID')),
                ('tag', models.CharField(max_length=300, verbose_name='Tag')),
                ('description', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Description')),
                ('exclusivity', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Exclusive to:')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OnlineLearner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('model_uuid', models.CharField(max_length=100, unique=True, verbose_name='Model UUID')),
                ('model_s3', models.CharField(blank=True, help_text='Format: bucket:filename', max_length=255, null=True, verbose_name='S3 Model address')),
                ('tag', models.CharField(max_length=300, verbose_name='Tag')),
                ('samples', jsonfield.fields.JSONField(blank=True, default=None, load_kwargs={'object_pairs_hook': collections.OrderedDict}, null=True)),
                ('positive_set_size', models.IntegerField(default=0)),
                ('pretrained', models.BooleanField(default=False, verbose_name='Pretrained')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('color_code', models.CharField(default='#f9f6fb', max_length=7)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LearnerAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('model_uuid', models.CharField(max_length=100, unique=True, verbose_name='Model UUID')),
                ('tag', models.CharField(max_length=300, verbose_name='Tag')),
                ('description', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Description')),
                ('name', models.CharField(blank=True, default='', max_length=300, verbose_name='Name')),
                ('output_range', jsonfield.fields.JSONField(blank=True, default=None, null=True)),
                ('parent_learner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learner_attribute', to='ml.PretrainedLearner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
