# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-25 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20170803_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regex',
            name='name',
            field=models.CharField(max_length=4096, unique=True),
        ),
    ]
