# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-28 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20170920_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordlist',
            name='name',
            field=models.CharField(max_length=4096, unique=True),
        ),
    ]
