# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-02 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_auto_20170928_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.SmallIntegerField(choices=[(0, b'RegEx'), (1, b'KeyWord')], default=0),
            preserve_default=False,
        ),
    ]
