# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-19 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_keywordlist_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.SmallIntegerField(choices=[(0, b'RegEx'), (1, b'KeyWord'), (2, b'SentSim')]),
        ),
    ]
