# Generated by Django 2.2 on 2021-02-26 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_auto_20180219_0809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='keyword',
            name='keyword_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='keywords', to='analysis.KeywordList'),
        ),
        migrations.AlterField(
            model_name='report',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reports', to='portal.Batch'),
        ),
        migrations.AlterField(
            model_name='report',
            name='json',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.SmallIntegerField(choices=[(0, 'RegEx'), (1, 'KeyWord'), (2, 'SentSim')]),
        ),
    ]
