# Generated by Django 2.2 on 2021-02-26 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_batchcollaborationinvite_projectcollaborationinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='access_token', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='batchcollaborationinvite',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='collaboration_invites', to='portal.Batch'),
        ),
        migrations.AlterField(
            model_name='batchcollaborationinvite',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='batch_collaboration_invites_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='batchcollaborationinvite',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='batch_collaboration_invites_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectcollaborationinvite',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_collaboration_invites_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectcollaborationinvite',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_collaboration_invites_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectcollaborationinvite',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='collaboration_invites', to='portal.Project'),
        ),
    ]
