---

- name: EC2
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars/base.yml
    - vars/secret.yml

  roles:
    - ec2
    - rds

  post_tasks:
    - wait_for: host="{{ item }}" port=22 search_regex=OpenSSH
      with_items: "{{ groups['tag_environment_' + env] }}"

  pre_tasks:
    - name: Check environment is valid
      fail: msg="Environment name must be 7 characters or shorter"
      when: "{{ env | length }} > 7"


- name: Provision
  user: ubuntu
  hosts: "tag_environment_{{ env | mandatory }}"
  gather_facts: false

  vars:
    ansible_ssh_extra_args: "-A"
    git_repo: git@github.com:BeagleInc/Rufus.git
    git_branch: master
    server_user: ubuntu
    setup_git_repo: yes

    # Database settings.
    db_user: "{{ application_name }}"
    db_name: "{{ application_name }}"
    db_password: password
    db_host: localhost
    db_port: 5432

    # Nginx settings.
    nginx_server_name: 127.0.0.1
    nginx_strong_dh_group: no

    # Django specific
    django_settings_file: "{{ application_name }}.settings"
    django_secret_key: "1^A9B5-E27CE5E$BB2p56B4p$dyD34F50E664_A18B"

    run_django_db_migrations: yes
    run_django_collectstatic: yes

    STATIC_ASSET_PATH: "{{ app_location }}/collectstatic"

  vars_files:
    - vars/base.yml
    - vars/secret.yml

  pre_tasks:
    - raw: sudo apt-get -y install python-simplejson
    - action: setup

    - apt:
        name="{{ item }}"
        state=latest
        update_cache=yes
        cache_valid_time=86400
      with_items:
        - acl
        - unattended-upgrades
      become: true
      become_user: root

    - gather_secrets:
      become: true
      become_user: root

  roles:
    - dynamic_vars
    - developer_access
    - base
    - web
    - postfix
    - nginx
    - supervisord
