# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-11 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_gitlab_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github_installation_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
