# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-18 15:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Promo Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('max_use_count', models.IntegerField(blank=True, help_text='Leave blank if no such restriction is desired', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='How many times the coupon can be used')),
                ('use_count', models.IntegerField(default=0, verbose_name='How many times the coupon has been used')),
                ('start_date', models.DateTimeField(blank=True, help_text='Optional', null=True, verbose_name='Coupon available from this date')),
                ('end_date', models.DateTimeField(blank=True, help_text='Optional', null=True, verbose_name='Coupon available until this date')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
