# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-19 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_bitbucket_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gitlab_refresh_token',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
