# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 08:02
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='content',
            field=jsonfield.fields.JSONField(),
        ),
    ]
