# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportshared'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('package_manager', models.CharField(max_length=20)),
                ('license', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='reportshared',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reportshared',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_shared', to='reports.Report'),
        ),
    ]
