# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20170711_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('treat_as', models.CharField(max_length=100, unique=True)),
                ('count', models.PositiveIntegerField()),
            ],
        ),
    ]
