# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-27 14:38
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20170717_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportshared',
            options={'verbose_name_plural': 'Shared Reports'},
        ),
        migrations.AddField(
            model_name='libstatistic',
            name='licenses',
            field=jsonfield.fields.JSONField(default=[]),
        ),
    ]
